### ISSUE TITLE
Thug Life 2

### ISSUE THREAD

**Issue by xZeroMCPE** [KairusDarkSeeker/OneInTheChamber#2]
Give me permission to read/write on this REPO only. And i"ll start working on OITC

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE lol OK, just make the PR and I'll merge it

**Comment by xZeroMCPE** [comment]
no lol i want direct access.

If not then, ill head my ways.

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE lmao

**Comment by xZeroMCPE** [comment]
lol i hate creating PR's

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE k I added u fam

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker Okay, now watch the magic!

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE don't fking ruin it

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker  Fk OFF!

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE LEL

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker -.- u better help contribute too lazy ass!!!

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE I will lmao

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE I have the plugin but it doesnt work

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker  You have skype?

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE no, only twitter

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker  oh.... u need skype. Anyways email me the plug and ill see what i can do with it!

andreleon911@gmail.com

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE k u better not redistribute it

**Comment by Dirtstuff** [comment]
Lol

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker no lol

**Comment by KairusDarkSeeker** [comment]
tf dirt

**Comment by Dirtstuff** [comment]
Who is Dirt?

**Comment by xZeroMCPE** [comment]
I wanted to create a group on github to store all awesome public plugins -.- 

All the good dev names are taken like github.com/PocketPlugin xD

**Comment by xZeroMCPE** [comment]
Ur DIRT lol

**Comment by KairusDarkSeeker** [comment]
@xZeroMCPE lmao let's just chat on Twitter rather than chatting on a dead issue

**Comment by xZeroMCPE** [comment]
@KairusDarkSeeker Alright, follow meh @xZeroMCPE on twitter!
